//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalFinance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categories
    {
        public Categories()
        {
            this.Transactions = new HashSet<Transactions>();
            this.Items = new HashSet<Item>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int CategoryTypesId { get; set; }
        public Nullable<decimal> Budget { get; set; }
    
        public virtual CategoryTypes CategoryType { get; set; }
        public virtual ICollection<Transactions> Transactions { get; set; }
        public virtual ICollection<Item> Items { get; set; }
    }
}
