//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalFinance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryTypes
    {
        public CategoryTypes()
        {
            this.Categories = new HashSet<Categories>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsCredit { get; set; }
    
        public virtual ICollection<Categories> Categories { get; set; }
    }
}
