//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalFinance.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PersonalFinanceContainer : DbContext
    {
        public PersonalFinanceContainer()
            : base("name=PersonalFinanceContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Categories> Categories { get; set; }
        public DbSet<CategoryTypes> CategoryTypes { get; set; }
        public DbSet<Transactions> Transactions { get; set; }
        public DbSet<Partners> Partners { get; set; }
        public DbSet<Item> Items { get; set; }
    }
}
