//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalFinance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transactions
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Amount { get; set; }
        public int CategoriesId { get; set; }
        public int PartnersId { get; set; }
    
        public virtual Categories Category { get; set; }
        public virtual Partners Partner { get; set; }
    }
}
